// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOTEyTPiedOjnce-KcEGU1NcyMDHoSz28',
    appId: '1:193945436265:web:1382cd10ef41b3657562f8',
    messagingSenderId: '193945436265',
    projectId: 'my-newsapp-flutter',
    authDomain: 'my-newsapp-flutter.firebaseapp.com',
    storageBucket: 'my-newsapp-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkyuupScTYsYq2WMEDFdvFmATA7p2pzZw',
    appId: '1:193945436265:android:2f42b79c580d8a527562f8',
    messagingSenderId: '193945436265',
    projectId: 'my-newsapp-flutter',
    storageBucket: 'my-newsapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1pOoSP_dBJLAhCdzfojgHeCUJ5Ed1u28',
    appId: '1:193945436265:ios:2c1fd18fe7b296667562f8',
    messagingSenderId: '193945436265',
    projectId: 'my-newsapp-flutter',
    storageBucket: 'my-newsapp-flutter.appspot.com',
    iosClientId: '193945436265-80lpmuc204rvqg3v1u6fg6urtnfmct91.apps.googleusercontent.com',
    iosBundleId: 'amartyaay.com.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1pOoSP_dBJLAhCdzfojgHeCUJ5Ed1u28',
    appId: '1:193945436265:ios:2c1fd18fe7b296667562f8',
    messagingSenderId: '193945436265',
    projectId: 'my-newsapp-flutter',
    storageBucket: 'my-newsapp-flutter.appspot.com',
    iosClientId: '193945436265-80lpmuc204rvqg3v1u6fg6urtnfmct91.apps.googleusercontent.com',
    iosBundleId: 'amartyaay.com.newsapp',
  );
}
